name: toynn
channels:
- conda-forge
- pytorch
dependencies:
- ca-certificates
- certifi
- cpuonly
- interrogate
- ipykernel
- ipywidgets
- jinja2
- jupyter
- jupyterlab
- matplotlib
- notebook
- numpy
- openssl
- python=3.11.7
- pytorch
- scipy
- setuptools
